# Generated by Django 4.1.1 on 2023-01-11 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_subscribecategories_delete_usercategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='sub_categories', through='news.SubscribeCategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
